name: build cpp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: build
      run: ./main.cpp
      
    - name: upload artefact
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
        path: main.exe
