name: build cpp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: build
      run: g++ main.cpp -o main

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: app_main
        # A file, directory or wildcard pattern that describes what to upload
        path: main
        retention-days: 10


  send:
      name: send
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: send telegram message
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            document: main
            message: |
              ${{ github.actor }} created commit:
              Commit message: ${{ github.event.commits[0].message }}

              Repository: ${{ github.repository }}

              See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
