name: build cpp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: build
      run: cl /EHsc main.cpp

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: main.cpp
        # A file, directory or wildcard pattern that describes what to upload
        path: main.exe
        retention-days: 10
        
        
        
    - name: Upload to Google Drive
    - uses: actions/download-artifact@v3
      with:
        name: main.cpp
    - name: send
      uses: satackey/action-google-drive@v1
      with:
        skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
        upload-from: ./
        upload-to: https://drive.google.com/drive/folders/1mMY-4OiAWBiUqOMJC2I3kcPJTCTqYwI8

        # For those who set up Google Drive API client ID and secret themselves
        google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
        google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
